spring:
  datasource:
    password: jayesh
    url: jdbc:mysql://localhost:3306/reportsdb?useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
